### ISSUE TITLE
Small line in some wiper variants...

### ISSUE THREAD

**Issue by moebiussurfing** [altschuler/imgui-knobs#10]
hey @altschuler ,
I made some customization of some parts to fit my style colors theme,

and I have noticed that in some types, a weird line is drawn.
Is that a "feature"?
It's a line in the center of the arc track:

https://user-images.githubusercontent.com/2106149/210727076-7846c5a8-472b-4292-bfa7-55c3cb17d5c2.mp4

Do you know how can I fix this and where to look into?

Thanks!

**Comment by altschuler** [comment]
Hi, good catch. I believe it's because the arc drawing isn't optimal when using transparency, since it's drawn in multiple overlapping segments. I'm sure it can be optimized somehow in here https://github.com/altschuler/imgui-knobs/blob/main/imgui-knobs.cpp#L39

**Comment by frink** [comment]
Basically you just need to draw the two parts as inverses so that they both move. I may be able to spend some time on that next week.

**Comment by altschuler** [comment]
> Basically you just need to draw the two parts as inverses so that they both move. I may be able to spend some time on that next week.

Can you clarify what you mean by drawing them as inverses?
