### ISSUE TITLE
Annoucing Dear ImGui Bundle including imgui-knobs and many others; with support for C++, Python and emscripten

### ISSUE THREAD

**Issue by pthom** [altschuler/imgui-knobs#11]
I'm happy to announce the first public release of Dear ImGui Bundle. Dear ImGui Bundle is a bundle for Dear ImGui, including many powerful libraries from its ecosystem. It enables to easily create ImGui applications in C++ *and* Python, under Windows, macOS, Linux, emscripten. It is aimed at application developers, researchers, and beginner developers who want to quickly get started.

imgui-knobs is a included in the widgets provided with it.

* [Dear ImGui Bundle repo](https://github.com/pthom/imgui_bundle/)
* [Fully interactive online manual](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html)
* [Specific annoucement for imgui-knobs integration](https://github.com/pthom/imgui_bundle/discussions/71)

@altschuler   : sorry to hijack the issues list for this, and feel to close this issue; as this is just for your information.  I informed @ocornut [yesterday](https://twitter.com/ocornut/status/1617963615503659008), and I plan to communicate about it in the [ImGui gallery](https://github.com/ocornut/imgui/issues/5886) in the next hours.

**Comment by altschuler** [comment]
Cool! Thanks for letting me know.

@DGriffin91 thought you might find this interesting as well :)

**Comment by DGriffin91** [comment]
@altschuler Thanks for the ping! Cool to see!
