### ISSUE TITLE
New dear imgui release breaks compilation

### ISSUE THREAD

**Issue by Madman10K** [altschuler/imgui-knobs#12]
Hello. First, thanks for creating and maintaining this really useful library!

The [newest dear imgui release v1.89.4](https://github.com/ocornut/imgui/releases/tag/v1.89.4) includes a breaking API change that renames the `AddBezierCurve` member of `ImDrawList` to `AddBezierCubic`

There is currently 1 instance of this in `imgui-knobs.cpp` at line `36` as part of the `draw_arc1` function. All that needs to be done is to replace `AddBezierCurve` with `AddBezierCubic`. 

This change was introduced in release [v1.80](https://github.com/ocornut/imgui/releases/tag/v1.80). I briefly looked through the changelog for any references to it, and it seems no changes to the API, other than the rename, were made since then, so it's safe to just rename.

I tested the change locally and everything works as expected with the example code from the readme.

**Comment by altschuler** [comment]
Thanks for the heads up! Would you be up for submitting a PR with the change? I think ImGui has some defines that lets us check the version at compile time, so we can support both versions.

**Comment by Madman10K** [comment]
PR open

**Comment by altschuler** [comment]
That was quick 🤩 thank you!
