### ISSUE TITLE
Where are the speed numbers for shift drag vs normal drag?

### ISSUE THREAD

**Issue by elanhickler** [altschuler/imgui-knobs#16]
Where in the code does this get decided? Having looked at the code for hours, still can't find it.

**Comment by elanhickler** [comment]
imgui_widgets.cpp look for DragBehaviorT function and adjust_delta variable under g.IO.KeyAlt or KeyShift if statements. Not sure if there's a way for me the programmer to affect this without changing the library code.

**Comment by altschuler** [comment]
Yeah, it's decided by the DragBehaviour. You pass in a speed and shift makes it x times faster (can't remember the factor). You might be able to set an ImGui value somewhere to adjust the shift speed up factor.
