### ISSUE TITLE
API discovery made harder by KNOB_WIDGET and KNOB_WIDGET_DEF ?

### ISSUE THREAD

**Issue by ocornut** [altschuler/imgui-knobs#3]
This is merely a suggestion, but I suspect that KNOB_WIDGET/KNOB_WIDGET_DEF are making it harder to:
- discover APIs
- use IDE facilities to follow through a function call
- search for code

Etc. this may throw off both tooling and humans alike. They seem to have rather minimal added value considering there are 7 entry points and being the same and declared in the same location, there have little reason to become out of sync.
I would therefore suggest to remove those macro indirection there.

It's also unclear what the detail:: stuff has to do in the public header file, since it seems unused (but also unsure what the VA_ARGS are for, so maybe part of that detail:: is required for public API).

**Comment by bkaradzic** [comment]
Please make it also dependency-free, and use struct instead of `std::pair` so that inclusion of utility.h is not needed.

**Comment by altschuler** [comment]
Thank you! I'll have a look at that, much appreciated :)

**Comment by altschuler** [comment]
This has been changed now, and the `<utility>` dependency has been changed. Thank you very much for the feedback, and let me know if you have any other suggestions 🙏

**Comment by ocornut** [comment]
Thank you for applying those changes, much appreciated !!
