### ISSUE TITLE
how to use int type?

### ISSUE THREAD

**Issue by moebiussurfing** [altschuler/imgui-knobs#4]
hey @altschuler ,
thanks a lot for sharing this!

do you know if we can use int types too?
I am trying but I am getting some rare behaviors....

**Comment by altschuler** [comment]
Hi, this has been implemented in https://github.com/altschuler/imgui-knobs/commit/f9c519dac84386dd21b0d31b4346b1ce2517360e. Please see the updated API, it now supports int knobs.

**Comment by moebiussurfing** [comment]
Thanks a lot for implementing all this new stuff.

I am adding your knobs to my [ImGui toolkit ](https://github.com/moebiussurfing/ofxSurfingImGui )for openFrameworks.

After updating now I am getting 4 errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2955	'ImGuiKnobs::detail::knob': use of class template requires template argument list	1_8_Knobs	c:\users\moebi\onedrive\documents\openframeworks\addons\ofxsurfingimgui\src\imgui\widgets\imgui-knobs.cpp	163	
Error	C2514	'ImGuiKnobs::detail::knob': class has no constructors	1_8_Knobs	c:\users\moebi\onedrive\documents\openframeworks\addons\ofxsurfingimgui\src\imgui\widgets\imgui-knobs.cpp	163	
Error	C2440	'return': cannot convert from 'ImGuiKnobs::detail::knob' to 'ImGuiKnobs::detail::knob<DataType>'	1_8_Knobs	c:\users\moebi\onedrive\documents\openframeworks\addons\ofxsurfingimgui\src\imgui\widgets\imgui-knobs.cpp	184	
Error	C2440	'return': cannot convert from 'ImGuiKnobs::detail::knob' to 'ImGuiKnobs::detail::knob<DataType>'	1_8_Knobs	c:\users\moebi\onedrive\documents\openframeworks\addons\ofxsurfingimgui\src\imgui\widgets\imgui-knobs.cpp	184	
```

Any idea how to fix it?

I am on Windows 10 / Visual Studio 2017.
using openFrameworks. I think it's c++ 11/14 maybe ....
dear imgui, v1.82

----

PS:

Also, I had to make some small fixes that trigger errors too.
Maybe you can update too if you think of "legacy bigger compatibility"...

```
        color_set GetSecondaryColorSet() {
            auto *colors = ImGui::GetStyle().Colors;

            //auto active = colors[ImGuiCol_ButtonActive] * ImVec4(0.5f, 0.5f, 0.5f, 1.f);
	    auto active = ImVec4(
		    colors[ImGuiCol_ButtonActive].x *0.5f,
		    colors[ImGuiCol_ButtonActive].y *0.5f,
		    colors[ImGuiCol_ButtonActive].z *0.5f,
		    1.f);

            //auto hovered = colors[ImGuiCol_ButtonHovered] * ImVec4(0.5f, 0.5f, 0.5f, 1.f);
	    auto hovered = ImVec4(
		    colors[ImGuiCol_ButtonHovered].x * 0.5f,
		    colors[ImGuiCol_ButtonHovered].y * 0.5f,
		    colors[ImGuiCol_ButtonHovered].z * 0.5f,
		    1.f);

            return {active, hovered, hovered};
        }
```

Also, I added to imgui-knobs.h:
`#define M_PI IM_PI`

**Comment by altschuler** [comment]
Thanks! I've pushed a fix, let me know if you still get any errors :)

**Comment by moebiussurfing** [comment]
thanks.
yes, it worked straightforwardly!
btw I noticed some rare behavior using the default speed.
like moving super fast on some knobs that were ranged from 0 to 1... not on a bigger range like -100 to 100 (maybe).
I am not sure bc I made a fast check.

**Comment by altschuler** [comment]
Yeah you're right, I've created a separate issue for it https://github.com/altschuler/imgui-knobs/issues/5. For now you can simply manually set the speed and use a higher value for bigger ranges (so eg speed 10 for [-100, 100] and 0.1 for [0, 1], or something like that).
